# Generated by Django 4.1.4 on 2023-07-10 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_files/')),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('exigence', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(max_length=50)),
                ('salaire', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('type_contrat', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCandidature', models.DateField(auto_now_add=True)),
                ('lettreMotivation', models.TextField()),
                ('statutCandidature', models.CharField(default='En attente', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.candidat')),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.emploi')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('nom_ecole', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='my_app.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.TextField()),
                ('poste', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='my_app.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('siren', models.IntegerField()),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emploi',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='my_app.entreprise'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='my_app.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_candidat', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_entreprise', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(to='my_app.message')),
            ],
            options={
                'unique_together': {('entreprise', 'candidat')},
            },
        ),
    ]
