# Generated by Django 4.1.4 on 2023-07-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_entreprise_siren_alter_entreprise_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
