# Generated by Django 4.1.4 on 2023-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_entreprise_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='siren',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
