# Generated by Django 4.1.4 on 2023-07-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_entreprise_siren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='siren',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
