# Generated by Django 4.1.4 on 2023-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_entreprise_email_alter_entreprise_siren_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='siren',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
