# Generated by Django 4.1.4 on 2023-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_entreprise_siren_alter_entreprise_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='poste',
            field=models.CharField(max_length=50),
        ),
    ]
