# Generated by Django 4.1.4 on 2023-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_experience_entreprise_alter_experience_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='titre',
            field=models.CharField(max_length=50),
        ),
    ]
